Pim\Component\Catalog\Model\VariantAttributeSet:
    constraints:
        - Pim\Component\Catalog\Validator\Constraints\Immutable:
            properties:
                - axes
            payload:
                standardPropertyName: variant_attribute_sets
